[project]
name = "update-lotomania"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Artur dos Santos Shon", email = "sky_artur@hotmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "csv-converter-skart>=0.2.2",
]

[project.scripts]
update-lotomania = "update_lotomania:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
